// import {
//   FaUserPlus,
//   FaTasks,
//   FaCheckCircle,
//   FaClock,
//   FaCalendarCheck,
//   FaUserEdit,
//   FaTools,
//   FaExclamationTriangle,
//   FaBuilding,
//   FaUsers,
// } from "react-icons/fa";




// export const notifications = [
//   {
//     id: 1,
//     icon:
//     title: "New Employee Added",
//     message: "Rahul Sharma has been added to the employee list.",
//     type: "success",
//     time: "2 min ago",
//     isRead: false,
//   },
//   {
//     id: 2,
//     title: "Task Assigned",
//      icon:  <FaCheckCircle   className="w-10 h-10   p-2 rounded-full bg-green-100 text-green-500"/>,
//     message: "A new task has been assigned to Priya Patel.",
//     type: "info",
//     time: "10 min ago",
//     isRead: false,
//   },
//   {
//     id: 3,
//     title: "Task Completed",
//      icon:  <FaCheckCircle  className="w-10 h-10   p-2 rounded-full bg-green-100 text-green-500"/>,
//     message: "Website redesign task has been completed.",
//     type: "success",
//     time: "30 min ago",
//     isRead: true,
//   },
//   {
//     id: 4,
//     title: "Deadline Reminder",
//      icon:  <FaClock  className="w-10 h-10   p-2 rounded-full bg-red-100 text-red-500"/>,
//     message: "Project Alpha deadline is tomorrow.",
//     type: "warning",
//     time: "1 hour ago",
//     isRead: false,
//   },
//   {
//     id: 5,
//     title: "Leave Request",
//      icon:  <FaCalendarCheck className="w-10 h-10   p-2 rounded-full bg-blue-100 text-blue-500" />,
//     message: "Sneha submitted a leave request.",
//     type: "info",
//     time: "2 hours ago",
//     isRead: true,
//   },
//   {
//     id: 6,
//     title: "Employee Updated",
//      icon:  <FaUserEdit className="w-10 h-10   p-2 rounded-full bg-orange-100 text-orange-500"/>,
//     message: "Amit updated his profile information.",
//     type: "info",
//     time: "3 hours ago",
//     isRead: false,
//   },
//   {
//     id: 7,
//     title: "System Maintenance",
//      icon:  <FaTools className="w-10 h-10   p-2 rounded-full bg-sky-100 text-sky-500"/>,
//     message: "Scheduled maintenance tonight at 11 PM.",
//     type: "warning",
//     time: "5 hours ago",
//     isRead: false,
//   },
//   {
//     id: 8,
//     title: "Task Overdue",
//      icon:  <FaExclamationTriangle   className="w-10 h-10   p-2 rounded-full bg-red-100 text-red-500"/>,
//     message: "Marketing campaign task is overdue.",
//     type: "error",
//     time: "6 hours ago",
//     isRead: false,
//   },
//   {
//     id: 9,
//     title: "New Department Created",
//      icon:  <FaBuilding className="w-10 h-10   p-2 rounded-full bg-purple-100 text-purple-500" />,
//     message: "Finance department has been created.",
//     type: "success",
//     time: "1 day ago",
//     isRead: true,
//   },
//   {
//     id: 10,
//     title: "Meeting Scheduled",
//      icon:  <FaUsers className="w-10 h-10   p-3 rounded-full bg-yellow-100 text-yellow-500"/>,
//     message: "Team meeting scheduled for Monday at 10 AM.",
//     type: "info",
//     time: "1 day ago",
//     isRead: false,
//   },
// ];